bot:
  token: "BOT-TOKEN"
  prefix: "!"
  activity:
    message: "Minecraft Tutorials"
    type: "PLAYING" #WATCHING; PLAYER; COMPETING; STREAMING
messages:
  warn:
    color: "#e24c4b"
  info:
    color: "#7c76e0"
  krunker:
    color: "#ebdb67"
ids:
  owners:
    - "357871005093462019"